import { execFileSync } from "node:child_process";
import { buildCards } from "./cards.js";
import { sameRepo } from "./feedback.js";
import type { ReviewCard } from "./types.js";

/**
 * PR write-back: turn a review card into a markdown comment a reviewer would
 * actually trust — verdict, claims-vs-evidence, findings, files, commands.
 * `foreman pr` posts it via the GitHub CLI; the inbox has a copy button for
 * everything else (GitLab, Bitbucket, email, carrier pigeon).
 */
export function buildPrComment(card: ReviewCard): string {
  const emoji = { critical: "🟥", high: "🟧", medium: "🟨", low: "🟩" }[card.level];
  const verdict =
    card.review === "approved"
      ? "✅ **Human-approved** in the Foreman inbox"
      : card.review === "flagged"
        ? `⚑ **Flagged by reviewer**${card.review_note ? ` — “${card.review_note}”` : ""}`
        : "⏳ Pending human review";

  const lines: string[] = [
    `## 🧑‍🏭 Foreman session evidence`,
    "",
    `${emoji} **Risk: ${card.level.toUpperCase()} (${card.score}/100)** · agent: \`${card.agent}\` · session \`${card.session.slice(0, 12)}\` · ${card.started.slice(0, 16).replace("T", " ")}`,
    "",
    verdict,
    "",
  ];

  if (card.claims.length) {
    lines.push(`### Claims vs evidence`);
    const badge = card.verified_claims
      ? "✅ backed by at least one passing verification command"
      : "❓ **UNVERIFIED** — no passing verification command in the session";
    for (const c of card.claims.slice(0, 5)) lines.push(`> “${c}”`);
    lines.push("", badge, "");
  }

  if (card.findings.length) {
    lines.push(`### Findings (${card.findings.length})`);
    for (const f of card.findings) lines.push(`- **${f.rule}** — ${f.detail}`);
    lines.push("");
  }

  if (card.files.length) {
    lines.push(`### Files touched (${card.files.length})`, "", "| File | Action | Lines |", "|---|---|---|");
    for (const f of card.files.slice(0, 25)) {
      lines.push(`| \`${f.path}\` | ${f.action} | ${f.lines_before ?? "—"} → ${f.lines_after ?? "—"} |`);
    }
    lines.push("");
  }

  if (card.commands.length) {
    const verifs = card.commands.filter((c) => c.verification);
    lines.push(
      `### Commands: ${card.commands.length} run, ${verifs.length} verification (${verifs.filter((c) => c.ok).length} passing)`
    );
    for (const c of verifs.slice(0, 8)) lines.push(`- ${c.ok ? "✓" : "✗"} \`${c.command.slice(0, 120)}\``);
    lines.push("");
  }

  if (card.mcp_calls > 0) {
    lines.push(`_${card.mcp_calls} MCP call(s) attested with signed receipts (\`foreman verify\`)._`, "");
  }
  lines.push(`---`, `_Generated by [Foreman](https://github.com/rohitkumarmanne-442/foreman) — the review inbox for your AI workforce._`);
  return lines.join("\n");
}

export function findCard(repo: string, sessionId?: string): ReviewCard | undefined {
  const cards = buildCards().filter((c) => !c.session.startsWith("demo-"));
  if (sessionId) return cards.find((c) => c.session === sessionId || c.session.startsWith(sessionId));
  return cards.filter((c) => sameRepo(c.cwd, repo)).sort((a, b) => b.started.localeCompare(a.started))[0];
}

/** Post the comment with the GitHub CLI. Returns the gh output. */
export function postToGitHub(repo: string, comment: string, prNumber?: string): string {
  const args = ["pr", "comment"];
  if (prNumber) args.push(prNumber);
  args.push("--body-file", "-");
  return execFileSync("gh", args, {
    cwd: repo,
    input: comment,
    encoding: "utf8",
    windowsHide: true,
  }).trim();
}
