import { spawn, spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { FOREMAN_HOME, ensureDirs } from "./paths.js";
import { startServer } from "./server.js";
import { buildCards } from "./cards.js";

/**
 * `foreman tray` — the inbox in your menu bar / system tray.
 *
 *  Windows  WinForms NotifyIcon (zero deps): live tooltip counts, balloon
 *           on new critical cards, click to open.
 *  macOS    a real menu-bar item via an xbar/SwiftBar plugin Foreman writes
 *           for you (both apps are free), plus native notifications through
 *           osascript for new critical cards.
 *  Linux    a tray icon via `yad` when available, otherwise notify-send
 *           notifications for new critical cards.
 *
 * Every path also runs the inbox server, so `foreman tray` is a complete
 * "leave it running" mode.
 */

export type TrayMode = "winforms" | "xbar" | "yad" | "notify";

export function getTrayMode(
  platform: NodeJS.Platform,
  env: { hasYad?: boolean; xbarDir?: string | null }
): TrayMode {
  if (platform === "win32") return "winforms";
  if (platform === "darwin") return env.xbarDir ? "xbar" : "notify";
  return env.hasYad ? "yad" : "notify";
}

/** xbar/SwiftBar plugin: a self-contained Node script that renders the
 * menu-bar item. The filename's `.15s.` suffix sets the refresh interval. */
export function buildXbarPlugin(port: number): string {
  return `#!/usr/bin/env node
// Foreman menu-bar plugin for xbar/SwiftBar — generated by \`foreman tray\`
const http = require("http");
http.get("http://127.0.0.1:${port}/api/cards", (res) => {
  let body = "";
  res.on("data", (c) => (body += c));
  res.on("end", () => {
    try {
      const cards = JSON.parse(body);
      const need = cards.filter((c) => c.review !== "approved");
      const crit = need.filter((c) => c.level === "critical").length;
      console.log(\`🧑‍🏭 \${need.length}\${crit ? "❗" : ""}\`);
      console.log("---");
      console.log(\`\${need.length} session(s) need review\${crit ? \` (\${crit} critical)\` : ""} | href=http://127.0.0.1:${port}\`);
      for (const c of need.slice(0, 5)) {
        const repo = String(c.cwd).split(/[\\\\/]/).filter(Boolean).pop();
        console.log(\`[\${c.level.toUpperCase()} \${c.score}] \${repo} | href=http://127.0.0.1:${port}\`);
      }
      console.log("Open inbox | href=http://127.0.0.1:${port}");
    } catch { console.log("🧑‍🏭 ?"); }
  });
}).on("error", () => {
  console.log("🧑‍🏭 –");
  console.log("---");
  console.log("Inbox offline — run: foreman tray | color=red");
});
`;
}

/** Native notification command per platform. */
export function buildNotifyArgs(platform: NodeJS.Platform, title: string, message: string): string[] {
  const t = title.replace(/"/g, "'");
  const m = message.replace(/"/g, "'");
  if (platform === "darwin") return ["osascript", "-e", `display notification "${m}" with title "${t}"`];
  return ["notify-send", "-u", "critical", t, m];
}

/** yad tray arguments (Linux). */
export function buildYadArgs(port: number): string[] {
  const url = `http://127.0.0.1:${port}`;
  return [
    "--notification",
    "--image=system-search",
    `--text=Foreman — the review inbox for your AI workforce`,
    `--command=xdg-open ${url}`,
    `--menu=Open inbox!xdg-open ${url}|Quit!quit`,
  ];
}

export function findXbarDir(home = os.homedir()): string | null {
  for (const p of [
    path.join(home, "Library", "Application Support", "xbar", "plugins"),
    path.join(home, "Library", "Application Support", "SwiftBar", "Plugins"),
  ]) {
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function hasCommand(cmd: string): boolean {
  const probe = process.platform === "win32" ? "where" : "which";
  return spawnSync(probe, [cmd], { stdio: "ignore" }).status === 0;
}

/** Poll for NEW critical cards and hand them to `onNew` (skips demo data,
 * skips everything already seen, primes silently on first pass). */
export function startCriticalWatcher(onNew: (c: { session: string; score: number; cwd: string }) => void): NodeJS.Timeout {
  const seen = new Set<string>();
  let primed = false;
  const tick = () => {
    try {
      for (const c of buildCards()) {
        if (c.level !== "critical" || c.review === "approved" || c.session.startsWith("demo-")) continue;
        if (seen.has(c.session)) continue;
        seen.add(c.session);
        if (primed) onNew(c);
      }
      primed = true;
    } catch { /* watcher must never take the tray down */ }
  };
  tick();
  const t = setInterval(tick, 10000);
  t.unref?.();
  return t;
}

export function runTray(port: number, iconPng?: string): void {
  ensureDirs();
  startServer(port);
  const url = `http://127.0.0.1:${port}`;
  const mode = getTrayMode(process.platform, {
    hasYad: process.platform === "linux" && hasCommand("yad"),
    xbarDir: process.platform === "darwin" ? findXbarDir() : null,
  });

  if (mode === "winforms") {
    console.log(`🧑‍🏭 Foreman tray running — inbox on ${url} (Exit via the tray menu)`);
    const script = buildWinScript(port, iconPng);
    const scriptPath = path.join(FOREMAN_HOME, "tray.ps1");
    fs.writeFileSync(scriptPath, script, "utf8");
    const child = spawn(
      "powershell",
      ["-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-File", scriptPath],
      { stdio: "ignore", windowsHide: true }
    );
    child.on("exit", () => process.exit(0));
    child.on("error", () => {
      console.error("Could not start the tray (PowerShell unavailable?) — server keeps running.");
    });
    return;
  }

  if (mode === "xbar") {
    const dir = findXbarDir()!;
    const pluginPath = path.join(dir, "foreman.15s.js");
    fs.writeFileSync(pluginPath, buildXbarPlugin(port), { mode: 0o755 });
    console.log(`🧑‍🏭 Menu-bar plugin installed → ${pluginPath}`);
    console.log(`   Refresh xbar/SwiftBar once and Foreman appears in your menu bar.`);
  } else if (mode === "yad") {
    const child = spawn("yad", buildYadArgs(port), { stdio: "ignore" });
    child.on("exit", () => process.exit(0));
    console.log(`🧑‍🏭 Tray icon running (yad) — inbox on ${url}`);
  } else {
    console.log(`🧑‍🏭 Foreman running — inbox on ${url}`);
    if (process.platform === "darwin") {
      console.log(`   Tip: install xbar (https://xbarapp.com) and rerun for a real menu-bar item.`);
    } else {
      console.log(`   Tip: install yad (apt install yad) and rerun for a real tray icon.`);
    }
  }

  console.log(`   Critical-card notifications are on. Ctrl+C to stop.`);
  startCriticalWatcher((c) => {
    const args = buildNotifyArgs(process.platform, "Foreman: critical session", `Risk ${c.score}/100 in ${c.cwd} — open ${url}`);
    try {
      spawn(args[0], args.slice(1), { stdio: "ignore", detached: true }).unref();
    } catch { /* notifier unavailable */ }
  });
}

function buildWinScript(port: number, iconPng?: string): string {
  const iconLine = iconPng
    ? `$bmp = New-Object System.Drawing.Bitmap "${iconPng.replace(/\\/g, "\\\\")}"; $icon = [System.Drawing.Icon]::FromHandle($bmp.GetHicon())`
    : `$icon = [System.Drawing.SystemIcons]::Information`;
  return `
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference = "SilentlyContinue"
$url = "http://127.0.0.1:${port}"
${iconLine}

$ni = New-Object System.Windows.Forms.NotifyIcon
$ni.Icon = $icon
$ni.Text = "Foreman - starting..."
$ni.Visible = $true

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$open = $menu.Items.Add("Open inbox")
$open.add_Click({ Start-Process $url })
$menu.Items.Add("-") | Out-Null
$exit = $menu.Items.Add("Exit Foreman")
$exit.add_Click({ $ni.Visible = $false; [System.Windows.Forms.Application]::Exit() })
$ni.ContextMenuStrip = $menu
$ni.add_MouseClick({ if ($_.Button -eq "Left") { Start-Process $url } })

$script:seen = @{}
$script:first = $true
$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = 10000
$timer.add_Tick({
  try {
    $cards = (Invoke-WebRequest -UseBasicParsing -TimeoutSec 4 "$url/api/cards").Content | ConvertFrom-Json
    $need = @($cards | Where-Object { $_.review -ne "approved" }).Count
    $crit = @($cards | Where-Object { $_.level -eq "critical" -and $_.review -ne "approved" }).Count
    $ni.Text = "Foreman - $need need review" + $(if ($crit) { " ($crit critical)" } else { "" })
    foreach ($c in $cards) {
      if ($c.level -eq "critical" -and $c.review -ne "approved" -and -not $c.session.StartsWith("demo-") -and -not $script:seen.ContainsKey($c.session)) {
        $script:seen[$c.session] = $true
        if (-not $script:first) {
          $ni.BalloonTipTitle = "Foreman: critical session"
          $ni.BalloonTipText = "Risk $($c.score)/100 in $($c.cwd) - click the tray to review"
          $ni.ShowBalloonTip(6000)
        }
      }
    }
    $script:first = $false
  } catch { $ni.Text = "Foreman - inbox unreachable" }
})
$timer.Start()

$ni.Text = "Foreman - watching your AI workforce"
[System.Windows.Forms.Application]::Run()
$timer.Stop()
$ni.Dispose()
`;
}
